# image: https://hub.docker.com/_/ghost

version: '3.8'

services:
  ghost:
    image: ghost:$APP_VERSION
    container_name: $APP_NAME
    restart: always
    ports:
      - $APP_HTTP_PORT:2368
    environment:
      - NODE_ENV=production
      # see https://ghost.org/docs/config/#configuration-options
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=$DB_MYSQL_USER
      - database__connection__password="$DB_MYSQL_PASSWORD"
      - database__connection__database=$DB_MYSQL_NAME
      # this url value is just an example, and is likely wrong for your environment!
      - url=http://$APP_URL
    volumes:
      - ghost:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mysql:$DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: always
    ports:
     - $DB_MYSQL_PORT:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_MYSQL_NAME
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_PASSWORD

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  ghost:
  mysql:
